name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Run basic script checks
      run: |
        Get-ChildItem *.bat | ForEach-Object {
          Write-Host "Checking $_"
          # Basic syntax check by attempting to parse
          $content = Get-Content $_ -Raw
          if ($content -match "powershell") {
            Write-Host "PowerShell command found in $_"
          }
        }

    - name: Check for required files
      run: |
        if (-not (Test-Path README.md)) { throw "README.md not found" }
        if (-not (Test-Path LICENSE)) { throw "LICENSE not found" }
        if (-not (Test-Path CONTRIBUTING.md)) { throw "CONTRIBUTING.md not found" }
        Write-Host "All required files present"
